language: cpp
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
install:
  - sudo apt-get install -y cmake
  - sudo apt-get install -y doxygen
script:
  - mkdir build && cd build && cmake .. && cmake --build
