language: cpp
compiler:
  - clang
  - gcc
os:
  - linux
install:
  - sudo apt-get install -y cmake3
  - sudo apt-get install -y doxygen
script:
  - mkdir build && cd build && cmake .. && cmake --build . && cpack