name: Build

on:
  push:
    branches:
    - master
    - develop
  pull_request:

jobs:
  ubuntu:
    strategy:
      matrix:
        config: [Debug, Release]
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: sudo apt-get install -y doxygen
      if: job.container.image == 'ubuntu-latest'
    - name: configure
      run: mkdir build && cd build && cmake .. -DCMAKE_INSTALL_PREFIX:PATH=~/.local -DLIBTELNET_STRICT:BOOL=NO
    - name: make
      run: cd build && cmake --build .
    - name: test
      run: cd build/test && ctest .
    - name: dist
      run: cd build && cpack -G TGZ
      if: false
