name: CI

on:
  push:
    branches:
    - master
    - develop
  pull_request:

jobs:
  Diagnose:
    runs-on: ubuntu-16.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
        
  Build:
    strategy:
      matrix:
        os: [ubuntu, windows, macOS]
        config: [Debug, Release]
  
    runs-on: ${{ matrix.os }}-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      shell: bash
      run: sudo apt-get install -y doxygen
      if: job.container.image == 'ubuntu-latest'
    - name: configure
      shell: bash
      run: mkdir build && cd build && cmake .. -DCMAKE_INSTALL_PREFIX:PATH=~/.local -DCMAKE_BUILD_TYPE:STRING=${CONFIG} -DLIBTELNET_STRICT:BOOL=${STRICT}
      env:
        CONFIG: ${{ matrix.config }}
        STRICT: NO
    - name: make
      shell: bash
      run: cd build && cmake --build .
    - name: test
      shell: bash
      run: cd build/test && ctest -C ${CONFIG} .
      env:
        CONFIG: ${{ matrix.config }}
    - name: dist
      shell: bash
      run: cd build && cpack -G TGZ
      if: false
